### ISSUE TITLE
babel-runtime/regenerator is missing

### ISSUE THREAD

**Issue by nettiopsu** [chrisvxd/story2sketch#21]
Hello,

story2sketch immediately crashed when I tried to run it for the first time, saying that babel-runtime/regenerator is not installed

Installing it globally with npm install -g babel-runtime solved the issue

`Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/story2sketch/lib/server/index.js:4:20)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)`

**Comment by chrisvxd** [comment]
Thanks @nettiopsu! Will investigate.

**Comment by miamollie** [comment]
I don't have much to add, but experiencing the same issue and the global install also solved it for me. :)

npm version `5.4.2`
node version `v8.6.0`
