### ISSUE TITLE
'WARNING: No matching node' Error

### ISSUE THREAD

**Issue by s10wen** [chrisvxd/story2sketch#80]
```
story2sketch --url http://localhost:6006/iframe.html?id=button--all --output stories.asketch.json
```

Here's the full log, if it's useful:
```
        ,,,,,,,,,,,,,...,,,,,,,,,,,,,
             **,,,,,,,,,,.......,,,,,,,,,,**
            ***,,,,,,,,...........,,,,,,,,***
          ****,,,,,,, ............. ,,,,,,,****
         *****.,,,, .               . ,,,,.*****
       *******.,,..                   ..,,.*******
      ******** ,.                      .., ********
     (((((////,***************************,////(((((
      ((///////,*************************,///////((
        ////////,***********************,////////
          ///////,*********************,///////
           ///////,*******************,///////
             //////,******,,,,,******,//////
               /////,*,,,,,,,,,,,,,*,/////
                 ////,,,,,,,,,,,,,,,////
                  ////,,,,,,,,,,,,,////
                    ///,,,,,,,,,,,///
                      //,,,,,,,,,//
                       //*,,,,,*//
                         /,,,,,/
                           *,*

                    story2sketch

Processing 12 stories...
 WARNING: No matching node for "Button/All" using querySelector #root on viewport narrow
 WARNING: No matching node for "Button/Primary" using querySelector #root on viewport narrow
 WARNING: No matching node for "Colour/Primary" using querySelector #root on viewport narrow
 WARNING: No matching node for "Button/All" using querySelector #root on viewport standard
[#-----------] 8% (1/12) 0.0s remaining WARNING: No matching node for "Button/Primary" using querySelector #root on viewport standard
 WARNING: No matching node for "Colour/Primary" using querySelector #root on viewport standard
 WARNING: No matching node for "Button/Secondary" using querySelector #root on viewport narrow
 WARNING: No matching node for "Button/Secondary" using querySelector #root on viewport standard
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:112:23)
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
  -- ASYNC --
    at Page.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:111:15)
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (…/.npm-packages/lib/node_modules/story2sketch/node_modules/core-js/library/modules/_export.js:36:28)
    at Story2sketch.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12) {
  name: 'TimeoutError'
}
TypeError: Cannot read property 'goto' of undefined
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (…/.npm-packages/lib/node_modules/story2sketch/node_modules/core-js/library/modules/_export.js:36:28)
    at Story2sketch.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Story2sketch.getSymbolsForStory (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:683:23)
TypeError: Cannot read property 'goto' of undefined
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (…/.npm-packages/lib/node_modules/story2sketch/node_modules/core-js/library/modules/_export.js:36:28)
    at Story2sketch.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Story2sketch.getSymbolsForStory (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:683:23)
TypeError: Cannot read property 'goto' of undefined
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (…/.npm-packages/lib/node_modules/story2sketch/node_modules/core-js/library/modules/_export.js:36:28)
    at Story2sketch.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Story2sketch.getSymbolsForStory (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:683:23)
TypeError: Cannot read property 'goto' of undefined
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (…/.npm-packages/lib/node_modules/story2sketch/node_modules/core-js/library/modules/_export.js:36:28)
    at Story2sketch.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Story2sketch.getSymbolsForStory (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:683:23)
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
    at runNextTicks (internal/process/task_queues.js:55:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
  -- ASYNC --
    at Frame.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:112:23)
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
  -- ASYNC --
    at Page.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:111:15)
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (…/.npm-packages/lib/node_modules/story2sketch/node_modules/core-js/library/modules/_export.js:36:28)
    at Story2sketch.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12) {
  name: 'TimeoutError'
}
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
    at runNextTicks (internal/process/task_queues.js:55:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
  -- ASYNC --
    at Frame.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:112:23)
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
  -- ASYNC --
    at Page.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:111:15)
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (…/.npm-packages/lib/node_modules/story2sketch/node_modules/core-js/library/modules/_export.js:36:28)
    at Story2sketch.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12) {
  name: 'TimeoutError'
}
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
  -- ASYNC --
    at Frame.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:112:23)
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
  -- ASYNC --
    at Page.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/puppeteer/lib/helper.js:111:15)
    at Story2sketch._callee5$ (…/.npm-packages/lib/node_modules/story2sketch/lib/server/Story2sketch.js:569:29)
    at tryCatch (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (…/.npm-packages/lib/node_modules/story2sketch/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at …/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (…/.npm-packages/lib/node_modules/story2sketch/node_modules/core-js/library/modules/_export.js:36:28)
    at Story2sketch.<anonymous> (…/.npm-packages/lib/node_modules/story2sketch/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12) {
  name: 'TimeoutError'
}
Success! 4 stories written to /…/stories.asketch.json
```

**Comment by s10wen** [comment]
the `stories.asketch.json` came out as:

```
{"_class":"page","do_objectID":"6aee0e46-8214-4481-b963-3c1b63af0a2b","exportOptions":{"_class":"exportOptions","exportFormats":[],"includedLayerIds":[],"layerOptions":0,"shouldTrim":false},"isFlippedHorizontal":false,"isFlippedVertical":false,"isLocked":false,"isVisible":true,"layerListExpandedType":0,"name":"Stories","nameIsFixed":false,"resizingConstraint":63,"resizingType":0,"rotation":0,"shouldBreakMaskChain":false,"layers":[],"clippingMaskMode":0,"hasClippingMask":false,"frame":{"_class":"rect","constrainProportions":false,"height":5000,"width":1920,"x":0,"y":0},"style":{"_class":"style","endDecorationType":0,"miterLimit":10,"startDecorationType":0},"horizontalRulerData":{"_class":"rulerData","base":0,"guides":[]},"verticalRulerData":{"_class":"rulerData","base":0,"guides":[]},"hasClickThrough":true,"includeInCloudUpload":true}
```
Importing to Sketch, I can see a 'Stories' page, but doesn't look to have any content in.

**Comment by s10wen** [comment]
Using Storybook 5.1.10

**Comment by s10wen** [comment]
I noticed in the README.md example the link is `https://localhost:9001/iframe.html`. I can individual stories e.g. at `http://localhost:6006/iframe.html?id=button--all`, but at `http://localhost:6006/iframe.html` I see 'No Preview'.

I'm wondering if there is an extra step I'm missing where I should see content at `http://localhost:6006/iframe.html`, or is the 'No Preview' expected behaviour?

**Comment by s10wen** [comment]
Made some progress 😍

Instead of running the `cli` command, I setup a `story2sketch.config.js` in the root:

```
module.exports = {
  output: "dist/great-ui.asketch.json",
  stories: "all",
  url: "http://localhost:6006/iframe.html"
};
```

Then ran `story2sketch` from the project root path. Doing so I had the error:
```
(node:32440) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '…/dist/great-ui.asketch.json'
```

I created the file and ran again and it worked :)

**Comment by s10wen** [comment]
Storybook View:

![Storybook](https://i.imgur.com/pMSE1jw.png)

Sketch View:

![Sketch](https://i.imgur.com/ZXAMLsO.png)

Not sure if there's an issue with the way I've got multiple components in a story, but looks to just be pulling in the first one.

**Comment by s10wen** [comment]
Example `Button.stories.js` code 'All' appears to be causing an issue and errors:

```
import React from 'react';
import { storiesOf } from '@storybook/react';
import Button from './Button';

storiesOf('Button', module)
  .add('All', () => (
    <React.Fragment>
      <Button
        style="primary"
        text="Primary Button"
      />
      <Button
        style="secondary"
        text="Secondary Button"
      />
    </React.Fragment>
  ))
  .add('Primary', () => (
    <Button
      style="primary"
      text="Primary Button"
    />
  ))
  .add('Secondary', () => (
    <Button
      style="secondary"
      text="Secondary Button"
    />
  ));
```

Remove the 'All', using the following code, seems to work:

```
import React from 'react';
import { storiesOf } from '@storybook/react';
import Button from './Button';

storiesOf('Button', module)
  .add('Primary', () => (
    <Button
      style="primary"
      text="Primary Button"
    />
  ))
  .add('Secondary', () => (
    <Button
      style="secondary"
      text="Secondary Button"
    />
  ));
```

**Comment by s10wen** [comment]
Hope that helps, apologies it's a bit scattered. Great project, I hope it continues to improve 👍🏻💫

**Comment by chrisvxd** [comment]
Hi @s10wen thanks for the all the info. Apologies for taking a while to respond.

So AFAIK storybook won't play well with multiple components per story since it assumes a 1 to 1 mapping between stories and symbols. You could try playing around with the `querySelector` param, but I haven't tried myself.

**Comment by s10wen** [comment]
Ah, good to know, I'm working on a large Storybook component library, so multiple would have been nice, can always split up. Cheers!

**Comment by bitfactory-lasse-vandenboschchristensen** [comment]
@chrisvxd @s10wen same issue here. As a test case i'm using a official Storybook demo storybook example:

```
module.exports = {
	output: "test.asketch.json",
	stories: "all",
	url:
		"https://airbnb.io/react-dates/iframe.html?id=daterangepicker-drp--default"
};
```
